// Auto-generated by Supabase MCP `generate_typescript_types`.
// Regenerate setiap kali schema berubah (PR #3+ akan re-run setelah migrasi).
//
// Source: project glbkdemanhkybwdlmjns @ 2026-05-01.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      babies: {
        Row: {
          birth_height_cm: number;
          birth_weight_kg: number;
          created_at: string;
          dob: string;
          gender: string;
          household_id: string;
          id: string;
          name: string;
          updated_at: string;
        };
        Insert: {
          birth_height_cm: number;
          birth_weight_kg: number;
          created_at?: string;
          dob: string;
          gender: string;
          household_id: string;
          id?: string;
          name: string;
          updated_at?: string;
        };
        Update: {
          birth_height_cm?: number;
          birth_weight_kg?: number;
          created_at?: string;
          dob?: string;
          gender?: string;
          household_id?: string;
          id?: string;
          name?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "babies_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      growth_measurements: {
        Row: {
          baby_id: string;
          created_at: string;
          created_by: string | null;
          head_circ_cm: number | null;
          height_cm: number;
          id: string;
          measured_at: string;
          notes: string | null;
          updated_at: string;
          weight_kg: number;
        };
        Insert: {
          baby_id: string;
          created_at?: string;
          created_by?: string | null;
          head_circ_cm?: number | null;
          height_cm: number;
          id?: string;
          measured_at: string;
          notes?: string | null;
          updated_at?: string;
          weight_kg: number;
        };
        Update: {
          baby_id?: string;
          created_at?: string;
          created_by?: string | null;
          head_circ_cm?: number | null;
          height_cm?: number;
          id?: string;
          measured_at?: string;
          notes?: string | null;
          updated_at?: string;
          weight_kg?: number;
        };
        Relationships: [
          {
            foreignKeyName: "growth_measurements_baby_id_fkey";
            columns: ["baby_id"];
            isOneToOne: false;
            referencedRelation: "babies";
            referencedColumns: ["id"];
          },
        ];
      };
      household_invitations: {
        Row: {
          accepted_at: string | null;
          created_at: string;
          expires_at: string;
          household_id: string;
          id: string;
          invited_by: string | null;
          invited_email: string;
          role: string;
          token: string;
        };
        Insert: {
          accepted_at?: string | null;
          created_at?: string;
          expires_at: string;
          household_id: string;
          id?: string;
          invited_by?: string | null;
          invited_email: string;
          role?: string;
          token: string;
        };
        Update: {
          accepted_at?: string | null;
          created_at?: string;
          expires_at?: string;
          household_id?: string;
          id?: string;
          invited_by?: string | null;
          invited_email?: string;
          role?: string;
          token?: string;
        };
        Relationships: [
          {
            foreignKeyName: "household_invitations_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      immunization_progress: {
        Row: {
          baby_id: string;
          created_by: string | null;
          facility: string | null;
          given_at: string;
          notes: string | null;
          vaccine_key: string;
        };
        Insert: {
          baby_id: string;
          created_by?: string | null;
          facility?: string | null;
          given_at: string;
          notes?: string | null;
          vaccine_key: string;
        };
        Update: {
          baby_id?: string;
          created_by?: string | null;
          facility?: string | null;
          given_at?: string;
          notes?: string | null;
          vaccine_key?: string;
        };
        Relationships: [
          {
            foreignKeyName: "immunization_progress_baby_id_fkey";
            columns: ["baby_id"];
            isOneToOne: false;
            referencedRelation: "babies";
            referencedColumns: ["id"];
          },
        ];
      };
      milestone_progress: {
        Row: {
          achieved_at: string;
          baby_id: string;
          created_by: string | null;
          milestone_key: string;
        };
        Insert: {
          achieved_at?: string;
          baby_id: string;
          created_by?: string | null;
          milestone_key: string;
        };
        Update: {
          achieved_at?: string;
          baby_id?: string;
          created_by?: string | null;
          milestone_key?: string;
        };
        Relationships: [
          {
            foreignKeyName: "milestone_progress_baby_id_fkey";
            columns: ["baby_id"];
            isOneToOne: false;
            referencedRelation: "babies";
            referencedColumns: ["id"];
          },
        ];
      };
      household_members: {
        Row: {
          household_id: string;
          joined_at: string;
          role: string;
          user_id: string;
        };
        Insert: {
          household_id: string;
          joined_at?: string;
          role?: string;
          user_id: string;
        };
        Update: {
          household_id?: string;
          joined_at?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "household_members_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      households: {
        Row: {
          created_at: string;
          created_by: string | null;
          id: string;
          name: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      logs: {
        Row: {
          amount_l_ml: number | null;
          amount_ml: number | null;
          amount_r_ml: number | null;
          baby_id: string;
          created_at: string;
          created_by: string | null;
          duration_l_min: number | null;
          duration_r_min: number | null;
          end_timestamp: string | null;
          has_pee: boolean | null;
          has_poop: boolean | null;
          id: string;
          med_dose: string | null;
          med_name: string | null;
          notes: string | null;
          poop_color: string | null;
          poop_consistency: string | null;
          subtype: string;
          temp_celsius: number | null;
          timestamp: string;
          updated_at: string;
        };
        Insert: {
          amount_l_ml?: number | null;
          amount_ml?: number | null;
          amount_r_ml?: number | null;
          baby_id: string;
          created_at?: string;
          created_by?: string | null;
          duration_l_min?: number | null;
          duration_r_min?: number | null;
          end_timestamp?: string | null;
          has_pee?: boolean | null;
          has_poop?: boolean | null;
          id?: string;
          med_dose?: string | null;
          med_name?: string | null;
          notes?: string | null;
          poop_color?: string | null;
          poop_consistency?: string | null;
          subtype: string;
          temp_celsius?: number | null;
          timestamp: string;
          updated_at?: string;
        };
        Update: {
          amount_l_ml?: number | null;
          amount_ml?: number | null;
          amount_r_ml?: number | null;
          baby_id?: string;
          created_at?: string;
          created_by?: string | null;
          duration_l_min?: number | null;
          duration_r_min?: number | null;
          end_timestamp?: string | null;
          has_pee?: boolean | null;
          has_poop?: boolean | null;
          id?: string;
          med_dose?: string | null;
          med_name?: string | null;
          notes?: string | null;
          poop_color?: string | null;
          poop_consistency?: string | null;
          subtype?: string;
          temp_celsius?: number | null;
          timestamp?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "logs_baby_id_fkey";
            columns: ["baby_id"];
            isOneToOne: false;
            referencedRelation: "babies";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      accept_household_invitation: {
        Args: { invite_token: string };
        Returns: string;
      };
      create_household_with_owner: {
        Args: { household_name: string };
        Returns: string;
      };
      list_household_members: {
        Args: { h_id: string };
        Returns: {
          email: string;
          joined_at: string;
          role: string;
          user_id: string;
        }[];
      };
      remove_household_member: {
        Args: { h_id: string; target_user_id: string };
        Returns: undefined;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
