// Auto-generated by Supabase MCP `generate_typescript_types`.
// Regenerate setiap kali schema berubah.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      babies: {
        Row: {
          birth_height_cm: number
          birth_weight_kg: number
          created_at: string
          dob: string
          gender: string
          household_id: string
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          birth_height_cm: number
          birth_weight_kg: number
          created_at?: string
          dob: string
          gender: string
          household_id: string
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          birth_height_cm?: number
          birth_weight_kg?: number
          created_at?: string
          dob?: string
          gender?: string
          household_id?: string
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "babies_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      growth_measurements: {
        Row: {
          baby_id: string
          created_at: string
          created_by: string | null
          head_circ_cm: number | null
          height_cm: number
          id: string
          measured_at: string
          notes: string | null
          updated_at: string
          weight_kg: number
        }
        Insert: {
          baby_id: string
          created_at?: string
          created_by?: string | null
          head_circ_cm?: number | null
          height_cm: number
          id?: string
          measured_at: string
          notes?: string | null
          updated_at?: string
          weight_kg: number
        }
        Update: {
          baby_id?: string
          created_at?: string
          created_by?: string | null
          head_circ_cm?: number | null
          height_cm?: number
          id?: string
          measured_at?: string
          notes?: string | null
          updated_at?: string
          weight_kg?: number
        }
        Relationships: [
          {
            foreignKeyName: "growth_measurements_baby_id_fkey"
            columns: ["baby_id"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
        ]
      }
      household_invitations: {
        Row: {
          accepted_at: string | null
          created_at: string
          expires_at: string
          household_id: string
          id: string
          invited_by: string | null
          invited_email: string
          role: string
          token: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          expires_at: string
          household_id: string
          id?: string
          invited_by?: string | null
          invited_email: string
          role?: string
          token: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          expires_at?: string
          household_id?: string
          id?: string
          invited_by?: string | null
          invited_email?: string
          role?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "household_invitations_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      household_members: {
        Row: {
          household_id: string
          joined_at: string
          role: string
          user_id: string
        }
        Insert: {
          household_id: string
          joined_at?: string
          role?: string
          user_id: string
        }
        Update: {
          household_id?: string
          joined_at?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "household_members_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      households: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          name: string
          sleep_playlist_url: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          sleep_playlist_url?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          sleep_playlist_url?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      immunization_progress: {
        Row: {
          baby_id: string
          created_by: string | null
          doctor_name: string | null
          facility: string | null
          given_at: string
          notes: string | null
          vaccine_key: string
        }
        Insert: {
          baby_id: string
          created_by?: string | null
          doctor_name?: string | null
          facility?: string | null
          given_at: string
          notes?: string | null
          vaccine_key: string
        }
        Update: {
          baby_id?: string
          created_by?: string | null
          doctor_name?: string | null
          facility?: string | null
          given_at?: string
          notes?: string | null
          vaccine_key?: string
        }
        Relationships: [
          {
            foreignKeyName: "immunization_progress_baby_id_fkey"
            columns: ["baby_id"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
        ]
      }
      logs: {
        Row: {
          amount_l_ml: number | null
          amount_ml: number | null
          amount_r_ml: number | null
          baby_id: string
          bottle_content: string | null
          consumed_ml: number
          created_at: string
          created_by: string | null
          duration_l_min: number | null
          duration_r_min: number | null
          end_l_at: string | null
          end_r_at: string | null
          end_timestamp: string | null
          has_pee: boolean | null
          has_poop: boolean | null
          id: string
          med_dose: string | null
          med_name: string | null
          notes: string | null
          poop_color: string | null
          poop_consistency: string | null
          start_l_at: string | null
          start_r_at: string | null
          subtype: string
          temp_celsius: number | null
          timestamp: string
          updated_at: string
        }
        Insert: {
          amount_l_ml?: number | null
          amount_ml?: number | null
          amount_r_ml?: number | null
          baby_id: string
          bottle_content?: string | null
          consumed_ml?: number
          created_at?: string
          created_by?: string | null
          duration_l_min?: number | null
          duration_r_min?: number | null
          end_l_at?: string | null
          end_r_at?: string | null
          end_timestamp?: string | null
          has_pee?: boolean | null
          has_poop?: boolean | null
          id?: string
          med_dose?: string | null
          med_name?: string | null
          notes?: string | null
          poop_color?: string | null
          poop_consistency?: string | null
          start_l_at?: string | null
          start_r_at?: string | null
          subtype: string
          temp_celsius?: number | null
          timestamp: string
          updated_at?: string
        }
        Update: {
          amount_l_ml?: number | null
          amount_ml?: number | null
          amount_r_ml?: number | null
          baby_id?: string
          bottle_content?: string | null
          consumed_ml?: number
          created_at?: string
          created_by?: string | null
          duration_l_min?: number | null
          duration_r_min?: number | null
          end_l_at?: string | null
          end_r_at?: string | null
          end_timestamp?: string | null
          has_pee?: boolean | null
          has_poop?: boolean | null
          id?: string
          med_dose?: string | null
          med_name?: string | null
          notes?: string | null
          poop_color?: string | null
          poop_consistency?: string | null
          start_l_at?: string | null
          start_r_at?: string | null
          subtype?: string
          temp_celsius?: number | null
          timestamp?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "logs_baby_id_fkey"
            columns: ["baby_id"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
        ]
      }
      medications: {
        Row: {
          created_at: string
          created_by: string | null
          default_dose: string | null
          household_id: string
          id: string
          name: string
          unit: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          default_dose?: string | null
          household_id: string
          id?: string
          name: string
          unit: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          default_dose?: string | null
          household_id?: string
          id?: string
          name?: string
          unit?: string
        }
        Relationships: [
          {
            foreignKeyName: "medications_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      milestone_progress: {
        Row: {
          achieved_at: string
          baby_id: string
          created_by: string | null
          milestone_key: string
        }
        Insert: {
          achieved_at?: string
          baby_id: string
          created_by?: string | null
          milestone_key: string
        }
        Update: {
          achieved_at?: string
          baby_id?: string
          created_by?: string | null
          milestone_key?: string
        }
        Relationships: [
          {
            foreignKeyName: "milestone_progress_baby_id_fkey"
            columns: ["baby_id"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_household_invitation: {
        Args: { invite_token: string }
        Returns: string
      }
      create_household_with_owner: {
        Args: { household_name: string }
        Returns: string
      }
      list_household_members: {
        Args: { h_id: string }
        Returns: {
          email: string
          joined_at: string
          role: string
          user_id: string
        }[]
      }
      remove_household_member: {
        Args: { h_id: string; target_user_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
