// Auto-generated by Supabase MCP `generate_typescript_types`.
// Regenerate setiap kali schema berubah (PR #3+ akan re-run setelah migrasi).
//
// Source: project glbkdemanhkybwdlmjns @ 2026-05-01.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      babies: {
        Row: {
          birth_height_cm: number;
          birth_weight_kg: number;
          created_at: string;
          dob: string;
          gender: string;
          household_id: string;
          id: string;
          name: string;
          updated_at: string;
        };
        Insert: {
          birth_height_cm: number;
          birth_weight_kg: number;
          created_at?: string;
          dob: string;
          gender: string;
          household_id: string;
          id?: string;
          name: string;
          updated_at?: string;
        };
        Update: {
          birth_height_cm?: number;
          birth_weight_kg?: number;
          created_at?: string;
          dob?: string;
          gender?: string;
          household_id?: string;
          id?: string;
          name?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "babies_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      household_invitations: {
        Row: {
          accepted_at: string | null;
          created_at: string;
          expires_at: string;
          household_id: string;
          id: string;
          invited_by: string | null;
          invited_email: string;
          role: string;
          token: string;
        };
        Insert: {
          accepted_at?: string | null;
          created_at?: string;
          expires_at: string;
          household_id: string;
          id?: string;
          invited_by?: string | null;
          invited_email: string;
          role?: string;
          token: string;
        };
        Update: {
          accepted_at?: string | null;
          created_at?: string;
          expires_at?: string;
          household_id?: string;
          id?: string;
          invited_by?: string | null;
          invited_email?: string;
          role?: string;
          token?: string;
        };
        Relationships: [
          {
            foreignKeyName: "household_invitations_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      household_members: {
        Row: {
          household_id: string;
          joined_at: string;
          role: string;
          user_id: string;
        };
        Insert: {
          household_id: string;
          joined_at?: string;
          role?: string;
          user_id: string;
        };
        Update: {
          household_id?: string;
          joined_at?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "household_members_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      households: {
        Row: {
          created_at: string;
          created_by: string | null;
          id: string;
          name: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          id?: string;
          name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      accept_household_invitation: {
        Args: { invite_token: string };
        Returns: string;
      };
      create_household_with_owner: {
        Args: { household_name: string };
        Returns: string;
      };
      list_household_members: {
        Args: { h_id: string };
        Returns: {
          email: string;
          joined_at: string;
          role: string;
          user_id: string;
        }[];
      };
      remove_household_member: {
        Args: { h_id: string; target_user_id: string };
        Returns: undefined;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
